# **Lab 20: Building a Quantum Simulator**
---

### **Description**
In this week's lab, we will see how to build our own quantum simulator using a new library: numpy.

<br>

### **Structure**
**Part 1**: [NumPy Arrays](#p1)
> **Part 1.1**: [General NumPy Arrays](#p1.1)

> **Part 1.2**: [States and Gates as NumPy Arrays](#p1.2)

**Part 2**: [The Quantum Simulator](#p2)
> **Part 2.1**: [Single Qubit Simulator](#p2.1)

> **Part 2.2**: [[ADVANCED] Multiple Qubit Simulator](#p2.2)

<br>

### **Learning Objectives**
By the end of this lab, we will:
* Recognize the basics of working with numpy arrays.

* Recognize how a simulator can be built using numpy.


<br>

### **Resources**
* [NumPy Simulator Cheat Sheet](https://docs.google.com/document/d/1kbO2xuZwD5LRyOmB5hOsMtbPxGdNC0ufdcXEACn_us0/edit?usp=sharing)

* [Cirq Cheat Sheet](https://docs.google.com/document/d/1j0vEwtS6fK-tD1DWAPry4tJdxEiq8fwMtXuYNGRhK_M)

<br>

**Before starting, run the code below to import all necessary functions and libraries.**


In [ ]:
import random
import matplotlib.pyplot as plt
import numpy as np

def binary_labels(num_qubits):
    return [bin(x)[2:].zfill(num_qubits) for x in range(2 ** num_qubits)]

<a name="p1"><a>

---

## **Part 1: NumPy Arrays**

---

<a name="p1.1"></a>

---

### **Part 1.1: General NumPy Arrays**

---

#### **Problem #1.1.1**

**Together**, let's create a numpy array from this list.

In [ ]:
example_list = [0,1,2,3,4]

numpy_array = np.array(example_list)

print(example_list)
print(numpy_array)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


#### **Problem #1.1.2**

**Together**, let's add the two arrays provided.

In [ ]:
array_1 = np.array([1, 0, -1])
array_2 = np.array([6, 0.5, 1])
# COMPLETE THIS CODE
array_1 + array_2

array([7. , 0.5, 0. ])

#### **Problem #1.1.3**

**Together**, let's square the provided array and output the result.

In [ ]:
example_list = [0, 2, 4, 6, 8, 10, 12]

numpy_array = np.array(example_list)

# COMPLETE THIS CODE
numpy_array ** 2

array([  0,   4,  16,  36,  64, 100, 144])

#### **Problem #1.1.4**

**Together**, let's create a numpy array representing the matrix below and output the element at index 2.

<br>


$\begin{bmatrix} 0 & 1 & 2 & 3 \\ 0 & 0 & 1 & 0 \\ -1.5 & 2 & 3 & 4 \end{bmatrix}$

In [ ]:
my_matrix = np.array([[0, 1, 2, 3], [0, 0, 1, 0], [-1.5, 2, 3, 4]]) # COMPLETE THIS CODE

# COMPLETE THIS CODE
my_matrix

array([[ 0. ,  1. ,  2. ,  3. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [-1.5,  2. ,  3. ,  4. ]])

#### **Problem #1.1.5**

**Independently**, create a numpy array with 10 numbers of your choice in a single row and print the result.

In [ ]:
# COMPLETE THIS CODE
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### **Problem #1.1.6**

**Independently**, complete the code below to square the array you made above and add it to the provided array.

In [ ]:
square_array = my_array ** 2

square_array# COMPLETE THIS CODE

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### **Problem #1.1.7**

**Independently**, create a numpy array representing the matrix below and output the element at index 1.


<br>


$\begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$

In [ ]:
box_array = np.array([[0,1], [1,0]])
box_array[1]

array([1, 0])

---

#### **Wait for your instructor to continue.**

---

#### **Problem #1.1.8**

**Together**, let's calculate two dot products with the given arrays:

1. array 1 dotted with array 2
2. array 2 dotted with array 1

<br>

**NOTE**: Pay attention to whether the results are the same or different.

In [ ]:
array_1 = np.array([0, 1, 2])
array_2 = np.array([1, 1, 1])

In [ ]:
np.dot(array_1, array_2)

5.0

In [ ]:
# COMPLETE THIS CODE
np.dot(array_2, array_1)

5.0

#### **Problem #1.1.9**

**Together**, let's calculate two dot products with the given arrays:

1. array 1 dotted with array 2
2. array 2 dotted with array 1


<br>

**NOTE**: Pay attention to whether the results are the same or different.

In [ ]:
array_1 = np.array([0, 1, 2])
array_2 = np.array([[1, 1, 1], [0, 0, 0], [0, 1, 2]])

In [ ]:
# COMPLETE THIS CODE
np.dot(array_1, array_2)

array([0, 2, 4])

In [ ]:
# COMPLETE THIS CODE
np.dot(array_2, array_1)

array([3, 0, 5])

#### **Problem #1.1.10**

**Independently**, calculate three dot products with the given arrays:

1. array 1 dotted with array 2
2. array 1 dotted with itself
3. array 2 dotted with itself

<br>

**NOTE**: Pay attention to whether the results are the same or different.

In [ ]:
array_1 = np.array([1, 0])
array_2 = np.array([1, 1])

In [ ]:
np.dot(array_1, array_2)

1

In [ ]:
# COMPLETE THIS CODE
np.dot(array_1, array_1)

1

In [ ]:
# COMPLETE THIS CODE
np.dot(array_2, array_2)

2

#### **Problem #1.1.11**

**Independently**, calculate three dot products with the given arrays:

1. array 1 dotted with array 2
2. array 2 dotted with array 1
2. array 2 dotted with itself

<br>

**NOTE**: Pay attention to whether the results are the same or different.

In [ ]:
array_1 = np.array([1, 2])
array_2 = np.array([[3, 4], [5, 6]])

In [ ]:
np.dot(array_1, array_2) # COMPLETE THIS CODE

array([13, 16])

In [ ]:
# COMPLETE THIS CODE
np.dot(array_2,array_1)

array([11, 17])

<a name="p1.2"><a>

---

### **Part 1.2: States and Gates as NumPy Arrays**

---

#### **Problem #1.2.1**

**Together**, let's create numpy arrays representing the $|0\rangle$ and $|1\rangle$ states and print them out.

In [ ]:
zero_state = np.array([1, 0])
one_state = np.array([0, 1])

In [ ]:
zero_state

array([1, 0])

In [ ]:
one_state

array([0, 1])

#### **Problem #1.2.2**

**Together**, let's create a numpy arrays representing the state $\frac{1}{\sqrt 3}(|0\rangle + \sqrt 2|1\rangle)$ and print it out.

In [ ]:
# state = (1/3**(1/2) * (zero_state)) + (2 ** (1/2) * (one_state))# COMPLETE THIS CODE
# state
state = 1/3 ** (1/2) * (zero_state + 2 ** (1/2) * one_state)
state

array([0.57735027, 0.81649658])

#### **Problem #1.2.3**

**Together**, let's take two dot products:

1. The $|0\rangle$ state with itself
2. The $|0\rangle$ state with the $|1\rangle$ state

In [ ]:
np.dot(# COMPLETE THIS CODE

In [ ]:
# COMPLETE THIS CODE

#### **Problem #1.2.4**

**Independently**, create numpy arrays representing the $|+\rangle$ and $|-\rangle$ states and print them out.

In [ ]:
plus_state = 1/(2)**(1/2) * (zero_state + one_state)# COMPLETE THIS CODE
plus_state
minus_state = 1/(2)**(1/2) * (zero_state - one_state)
minus_state

array([ 0.70710678, -0.70710678])

In [ ]:
plus_state

In [ ]:
minus_state

#### **Problem #1.2.5**

**Independently**, create a numpy array representing the state $\frac{1}{5}(3|+\rangle + 4|-\rangle)$ and print it out.

In [ ]:
# COMPLETE THIS CODE

#### **Problem #1.2.6**

**Independently**, take the following dot products:

1. The $|+\rangle$ state with itself
2. The $|+\rangle$ state with the $|0\rangle$ state
3. The $|-\rangle$ state with the $|1\rangle$ state
4. The $|+\rangle$ state with the $|-\rangle$ state

In [ ]:
# COMPLETE THIS CODE

In [ ]:
# COMPLETE THIS CODE

In [ ]:
# COMPLETE THIS CODE

In [ ]:
# COMPLETE THIS CODE

---

#### **Wait for your instructor to continue.**

---

#### **Problem #1.2.7**

**Together**, let's create a numpy array representing the X gate and take the dot product of the X gate with the $|1\rangle$ state.

<br>

**NOTE**: The matrix for the X gate is:
$\begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$

In [ ]:
x_gate = np.array([[0,1], [1,0]])# COMPLETE THIS CODE

np.dot(x_gate, one_state)# COMPLETE THIS CODE

array([1, 0])

#### **Problem #1.2.8**

**Independently**, create a numpy array representing the Identity gate and take the dot product of the Identity gate with the $|0\rangle$ state.

<br>

**NOTE**: The matrix for the Identity gate is:
$\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

In [ ]:
id_gate = np.array([[1,0], [0,1]])
np.dot(id_gate, zero_state)
# COMPLETE THIS CODE

array([1, 0])

#### **Problem #1.2.9**

**Independently**, create a numpy array representing the H gate and take the dot product of the H gate with the $|1\rangle$ state.

<br>

**NOTE**: The matrix for the H gate is:
$\frac{1}{\sqrt 2} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}$

In [ ]:
h_gate = 1/2**(1/2) * np.array([[1, 1], [1, -1]])# COMPLETE THIS CODE

# COMPLETE THIS CODE
np.dot(h_gate, one_state)

array([ 0.70710678, -0.70710678])

#### **Problem #1.2.10**

**Independently**, take the dot product of the H gate with the $|-\rangle$ state.

In [ ]:
# COMPLETE THIS CODE
np.dot(h_gate, minus_state)

array([2.23711432e-17, 1.00000000e+00])

---

#### **Wait for your instructor to continue.**

---

#### **Problem #1.2.11**

**Together**, let's calculate the probability of measuring 0 in the $|+\rangle$ state.

<br>



In [ ]:
probabilities = plus_state ** 2 # COMPLETE THIS CODE
probabilities[0]

0.4999999999999999

#### **Problem #1.2.12**

**Together**, let's calculate the probability of measuring 1 after applying the H gate to the minus state.

<br>



In [ ]:
probabilities = minus_state ** 2
probabilities[1]

0.4999999999999999

#### **Problem #1.2.13**

**Independently**, calculate the probability of measuring 0 in the state $\frac{1}{5}(3|0\rangle + 4|1\rangle)$.

<br>



In [ ]:
state = (1/5) * (3 * zero_state + 4 * one_state)

probabilities = state ** 2
probabilities[0]

0.3600000000000001

<a name="p2"><a>

---

## **Part 2: The Quantum Simulator**

---

<a name = "p2.1"></a>

---

### **Part 2.1: Single Qubit Simulator**

---

**Run the code below to ensure all the states and gates from above are defined.**

In [ ]:
zero_state = np.array([1, 0])
one_state = np.array([0, 1])
plus_state = 1/2**(1/2) * np.array([1, 1])
minus_state = 1/2**(1/2) * np.array([1, -1])


id_gate = np.array([[1, 0], [0, 1]])
x_gate = np.array([[0, 1], [1, 0]])
h_gate = 1/2**(1/2) * np.array([[1, 1], [1, -1]])

#### **Problem #2.1.1**

**Together**, let's combine what we've learned above to produce a list of measurement probabilities after applying the gates in the `circuit` list to the zero state.

In [ ]:
state = zero_state
circuit = [x_gate, h_gate]

for gate in circuit:

  state = np.dot(zero_state, gate)

print(state)

probabilities = state ** 2
probabilities

[0.70710678 0.70710678]


array([0.5, 0.5])

#End of notebook
---
© 2024 The Coding School, All rights reserved